# Generated by Django 5.1.7 on 2025-03-11 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_quiz_quizquestion_quizoption_quizsubmission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizsubmission',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quizanswer',
            name='selected_option',
        ),
        migrations.RemoveField(
            model_name='quizanswer',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='quizoption',
            name='question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizAnswer',
        ),
        migrations.DeleteModel(
            name='QuizSubmission',
        ),
        migrations.DeleteModel(
            name='QuizOption',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
    ]
