# Generated by Django 5.1.7 on 2025-03-11 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_question_choice_quiz_question_quiz_quizsubmission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='child',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='quizsubmission',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizSubmission',
        ),
    ]
