# Generated by Django 5.1.7 on 2025-03-09 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('child', '0001_initial'),
        ('guardian', '0001_initial'),
        ('trainer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guardian.guardian'),
        ),
        migrations.AddField(
            model_name='child',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='childskill',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child.child'),
        ),
        migrations.AddField(
            model_name='task',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='child.child'),
        ),
        migrations.AddField(
            model_name='task',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='trainer.trainer'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='child.task'),
        ),
        migrations.AddField(
            model_name='trainerassignment',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_assignments', to='child.child'),
        ),
        migrations.AddField(
            model_name='trainerassignment',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_children', to='trainer.trainer'),
        ),
        migrations.AlterUniqueTogether(
            name='trainerassignment',
            unique_together={('child', 'trainer', 'subject', 'skill')},
        ),
    ]
