# Generated by Django 5.1.7 on 2025-03-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='allergy_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='current_medication',
            field=models.TextField(blank=True, null=True),
        ),
    ]
